analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#aead91'
    - '#bb4c5c'
    - '#2e231f'
    - '#647495'
  brandStrength: 0.875
  lightness: 0.1933135858271271
  rhythmicContrast: 0.08383217779919505
  saturation: 0.19009372522123158
cta: {}
layout_spectrum: 0.744243
name: edd
opengraph: {}
purpose: []
typography_spectrum: 0.43834
