name: edd
favicon: null
layout_spectrum: 0.49422
typography_spectrum: 0.50771
title: "Edd's first Grid site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aead91'
    - '#bb4c5c'
    - '#2e231f'
    - '#647495'
  brandStrength: 0.875
  lightness: 0.1933135858271271
  saturation: 0.19009372522123158
  rhythmicContrast: 0.08383217779919505
purpose: []
