name: edd
favicon: null
layout_spectrum: 0.49422
typography_spectrum: 0.50771
title: "Edd's first Grid site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff3'
    - '#645f66'
    - '#9f9b98'
    - '#c6c6c6'
    - '#14181b'
  brandStrength: 0.875
  lightness: 0.1933135858271271
  saturation: 0.19009372522123158
  rhythmicContrast: 0.08383217779919505
purpose: []
