name: edd
favicon: null
layout_spectrum: 0.49531502090394497
typography_spectrum: 0.5289830164983869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9275858183391392
  lightness: 0.1933135858271271
  saturation: 0.19009372522123158
  rhythmicContrast: 0.08383217779919505
purpose: []
