typography_spectrum: 0.43834
color:
  brandColors:
    - '#ffffff'
    - '#aead91'
    - '#bb4c5c'
    - '#2e231f'
    - '#647495'
  brandStrength: 0.875
  lightness: 0.1933135858271271
  rhythmicContrast: 0.08383217779919505
  saturation: 0.19009372522123158
opengraph: {}
layout_spectrum: 0.744243
analytics: {}
name: edd
cta: {}
title: Testing this out
description: Rougher than you think
purpose: []
